SELECT 
[NF_NOMEENTIDADE] AS corporate_name, 
[NF_NUMDOCUM] AS invoice_id, 
[NF_DATAEMIS] AS issue_date, 
NF.[ID_CODENTIDADE] AS client_id,
E.[ENTI_CNPJCPF] AS client_cnpj,
NF.[ID_CODTRANSP] AS transporter_id
FROM [NOTAFISCAL] NF
INNER JOIN [ENTIDADES] E ON NF.[ID_CODENTIDADE] = E.[ID_CODENTIDADE]
WHERE NF.[ID_CODFILIAIS] = 1
AND NF.[ID_CODTRANSP] NOT IN (0)
AND NF.[NF_DATAEMIS] >= @dataFrom
AND NF.[NF_DATAEMIS] <= @dataTo